import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Content from "../components/Content";
import requests from "../utils/requests";

export default function Home({ data }) {
  console.log(data);
  return (
    <div>
      <Head>
        <title>Hulu v2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Content content={data} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const { gener } = context.query;
  const data = await fetch(
    `https://api.themoviedb.org/3${
      requests[gener]?.url || requests.ferchTrending.url
    }`
  ).then((res) => res.json());
  return {
    props: {
      data: data.results,
    },
  };
}
